table dim_drivers
	lineageTag: 6f3a3f65-165e-4f10-bd27-261592ab9cca

	column driver_id
		dataType: int64
		formatString: 0
		lineageTag: 6629a294-4bab-4c06-900b-fce910e17933
		summarizeBy: none
		sourceColumn: driver_id

		annotation SummarizationSetBy = Automatic

	column driver_modal
		dataType: string
		lineageTag: 0e17cbc4-a28f-43af-9f47-53386e48e194
		summarizeBy: none
		sourceColumn: driver_modal

		annotation SummarizationSetBy = Automatic

	column driver_type
		dataType: string
		lineageTag: c6e2d170-63c8-473e-8201-128dd357a7bf
		summarizeBy: none
		sourceColumn: driver_type

		annotation SummarizationSetBy = Automatic

	column total_delivery_distance_km
		dataType: double
		lineageTag: 0150ce00-121d-44d8-aeac-ebc28a7f2431
		summarizeBy: none
		sourceColumn: total_delivery_distance_km

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_deliveries
		dataType: int64
		formatString: 0
		lineageTag: f06542c3-f06a-4dab-9991-e925040a02e9
		summarizeBy: none
		sourceColumn: total_deliveries

		annotation SummarizationSetBy = Automatic

	partition dim_drivers = m
		mode: import
		source =
				let
				    Fonte = Value.NativeQuery(PostgreSQL.Database("localhost", "postgres"), "SELECT *#(lf)FROM dc_gold.dim_drivers", null, [EnableFolding=true]),
				    #"Drop ingestion_timestamp" = Table.RemoveColumns(Fonte,{"ingestion_timestamp"})
				in
				    #"Drop ingestion_timestamp"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

